### ISSUE TITLE
Wamp Delegate close session with code 1000 and reason nil

### ISSUE THREAD

**Issue by kaka09** [mogui/MDWamp#26]
Hi Mogui!
I appreciated what you have done.
Sometime I have been closed socket, I dont know why.
After debuging, I found return code is 1000, reason nil. Do you know about this?
Thanks!

**Comment by kaka09** [comment]
Hi mogui,
Long time no see :), I come back to close. You're right about the issue. Thanks.

**Comment by mogui** [comment]
:) great !
