### ISSUE TITLE
Negative request IDs

### ISSUE THREAD

**Issue by garbatix** [mogui/MDWamp#32]
I try to use library in my Swift app and sometimes I receive errors resulting in closing connection. The problem is in generator of random numbers in MDWamp.m function: - (NSNumber *) generateID
which generates negative numbers (not always). There should be something wrong with them under Swift compiler or something.

Session closed: [NSLocalizedDescription: WAMP Protocol Error ('request' in CALL: invalid value -312046319 for ID)] code: 1002reason: WAMP Protocol Error ('request' in CALL: invalid value -312046319 for ID)

I have realized that [NSNumber numberWithInt:r] does its work wrong.

Solution is to change the above to:

[NSNumber numberWithUnsignedInt:r];

**Comment by mogui** [comment]
it's a regression within the last commit I'll fix it quickly, 
thanks

**Comment by asdlars** [comment]
This is still an issue in CocoaPods. Please commit to it too.

**Comment by kilabyte** [comment]
this bug still resides in the cocoa pods. MDWamp.m Line 106.

**Comment by girishnair12345** [comment]
I am still facing this issue please fix it

**Comment by mogui** [comment]
@asdlars @kilabyte sorry for the delay
now is online correctly, be sure to use version 2.2.2
