### ISSUE TITLE
MDWamp reconnection error

### ISSUE THREAD

**Issue by girishnair12345** [mogui/MDWamp#39]
I am using the MDWamp for swift using cocopods. I initalize and connect it to server using wampcra and connect it using         self.wamp?.connect() and things work fine

But If i try to disconnect and reconnect the it throws the following error

*** Assertion failure in -[SRWebSocket open], …. Pods/SocketRocket/SocketRocket/SRWebSocket.m:389

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot call -(void)open on SRWebSocket more than once'

I can disconnect without any problem but problem occurs when I reconnect it

**Comment by girishnair12345** [comment]
When the internet is down and I try to connect I get 
Session Closed  Code: 50
Reason: The operation couldn’t be completed. Network is down

Once and when I reconnect with internet it just doesn't connect automatically and there is no method for reconnection in your code? and If i try to call connect then it shows the above exception

**Comment by girishnair12345** [comment]
Will you please reply ?

**Comment by mogui** [comment]
Hi @girishnair12345  sorry for the long wait,
I'm trying to reproduce your issue, but I could not face it.
that exception is thrown by the underlying library SocketRocket and it means that you're calling connect to an already opened connection, you don't call disconnect correctly.
To have a try on that try running the demo app and connect and disconnect you'll see that you can do it smootly also by loosing connection to the server. Notice that you'll have delegate methods to catch when the client disconnects.
It is true that it does not automatically reconnect when loosing connection, but you can easily implement it by catching disconnection by using the aformentioned delegate/block

let me know if you're still having problems, maybe helping me out to reproduce the problem with more details

**Comment by girishnair12345** [comment]
The demo project that you have doesnt run
files are missing in that

Anyway I have created a demo and here is the [link](https://www.dropbox.com/s/kyn3f7u4abqgcrt/TestMDWamp.zip?dl=0)

There some changes though
I needed to add a custom header so I have made another initalizer  as follows in *MDWampTransport.h*

```
- (id)initWithRequest:(NSMutableURLRequest *)request protocolVersions:(NSArray *)protocols;


- (id)initWithRequest:(NSMutableURLRequest *)request protocolVersions:(NSArray *)protocols
{
    self = [super init];
    if (self) {
        NSAssert([protocols count] > 0, @"Specify a valid WAMP protocol");
        
        NSAssert(([protocols containsObject:kMDWampProtocolWamp2json]
                  ||[protocols containsObject:kMDWampProtocolWamp2msgpack]), @"No valid WAMP protocol found");
        
        self.socket = [[SRWebSocket alloc] initWithURLRequest:request protocols:protocols ];
        [_socket setDelegate:self];
    }
    return self;
}
```

Also changed the category for *MDString* with this *CC_SHA1_DIGEST_LENGTH* to *CC_SHA256_DIGEST_LENGTH*

*NSString (MDString)*
```
    return [[NSData dataWithBytes:cHMAC length:CC_SHA256_DIGEST_LENGTH] base64EncodedStringWithOptions:0];
```

Now When i click connect I get this log
> 2016-01-20 12:47:55.646 TestMDWamp[4812:44002] -[MDWampTransportWebSocket webSocketDidOpen:] negotiated protocol is wamp.2.json
> 2016-01-20 12:47:55.646 TestMDWamp[4812:44002] -[MDWamp transportDidOpenWithSerialization:] websocket connection opened
> 2016-01-20 12:47:55.647 TestMDWamp[4812:44002] -[MDWamp sendMessage:] Sending <MDWampHello: 0x7c224ad0>
> 2016-01-20 12:47:55.657 TestMDWamp[4812:44002] -[MDWamp sendMessage:] Sending <MDWampAuthenticate: 0x7c225e50>
> Session Established


On Disconnect I get this
> Session Closed  Code: 1
> Reason: MDWamp.session.explicit_closed
> 2016-01-20 12:48:16.753 TestMDWamp[4812:44002] -[MDWamp transportDidCloseWithError:] DID CLOSE reason Stream end encountered


Now when I call connect again I get this
> 2016-01-20 12:48:56.485 TestMDWamp[4904:44535] *** Assertion failure in -[SRWebSocket open], /Users/ahazra/Desktop/TestMDWamp/Pods/SocketRocket/SocketRocket/SRWebSocket.m:389
> 2016-01-20 12:48:56.489 TestMDWamp[4904:44535] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot call -(void)open on SRWebSocket more than once'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x003c9a14 __exceptionPreprocess + 180
> 	1   libobjc.A.dylib                     0x0207de02 objc_exception_throw + 50
> 	2   CoreFoundation                      0x003c98aa +[NSException raise:format:arguments:] + 138
> 	3   Foundation                          0x00805d26 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
> 	4   SocketRocket                        0x0023e5fb -[SRWebSocket open] + 379
> 	5   MDWamp                              0x001da076 -[MDWampTransportWebSocket open] + 54
> 	6   MDWamp                              0x001c1880 -[MDWamp connect] + 80
> 	7   TestMDWamp                          0x000767ba _TFC10TestMDWamp14ViewController7connectfS0_FT_T_ + 170
> 	8   TestMDWamp                          0x00076802 _TToFC10TestMDWamp14ViewController7connectfS0_FT_T_ + 34
> 	9   libobjc.A.dylib                     0x020920b5 -[NSObject performSelector:withObject:withObject:] + 84
> 	10  UIKit                               0x00baeb79 -[UIApplication sendAction:to:from:forEvent:] + 118
> 	11  UIKit                               0x00baeaf8 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
> 	12  UIKit                               0x00d4e8f8 -[UIControl sendAction:to:forEvent:] + 79
> 	13  UIKit                               0x00d4ec78 -[UIControl _sendActionsForEvents:withEvent:] + 408
> 	14  UIKit                               0x00d4dc7e -[UIControl touchesEnded:withEvent:] + 714
> 	15  UIKit                               0x00c2b182 -[UIWindow _sendTouchesForEvent:] + 1095
> 	16  UIKit                               0x00c2c220 -[UIWindow sendEvent:] + 1159
> 	17  UIKit                               0x00bd0f93 -[UIApplication sendEvent:] + 266
> 	18  UIKit                               0x00ba6668 _UIApplicationHandleEventQueue + 7802
> 	19  CoreFoundation                      0x002e36ff __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
> 	20  CoreFoundation                      0x002d938b __CFRunLoopDoSources0 + 523
> 	21  CoreFoundation                      0x002d87a8 __CFRunLoopRun + 1032
> 	22  CoreFoundation                      0x002d80e6 CFRunLoopRunSpecific + 470
> 	23  CoreFoundation                      0x002d7efb CFRunLoopRunInMode + 123
> 	24  GraphicsServices                    0x04861664 GSEventRunModal + 192
> 	25  GraphicsServices                    0x048614a1 GSEventRun + 104
> 	26  UIKit                               0x00bacbfa UIApplicationMain + 160
> 	27  TestMDWamp                          0x0007908c main + 140
> 	28  libdyld.dylib                       0x03710a21 start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by girishnair12345** [comment]
Now When I trun off the network and connect
> 2016-01-20 13:23:35.511 TestMDWamp[5359:56314] -[MDWamp transportDidFailWithError:] DID FAIL reason The operation couldn’t be completed. Network is down
> Session Closed  Code: 50
> Reason: The operation couldn’t be completed. Network is down

and i press connect again,
> 2016-01-20 13:23:54.483 TestMDWamp[5359:56314] *** Assertion failure in -[SRWebSocket open], <PATH>/Pods/SocketRocket/> SocketRocket/SRWebSocket.m:389
> 2016-01-20 13:23:54.488 TestMDWamp[5359:56314] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot call -(void)open on SRWebSocket more than once'
> *** First throw call stack:
> (
>     0   CoreFoundation                      0x00383a14 __exceptionPreprocess + 180
>     1   libobjc.A.dylib                     0x02037e02 objc_exception_throw + 50
>     2   CoreFoundation                      0x003838aa +[NSException raise:format:arguments:] + 138
>     3   Foundation                          0x007bfd26 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
>     4   SocketRocket                        0x001f85fb -[SRWebSocket open] + 379
>     5   MDWamp                              0x00194076 -[MDWampTransportWebSocket open] + 54
>     6   MDWamp                              0x0017b880 -[MDWamp connect] + 80
>     7   TestMDWamp                          0x0003199a _TFC10TestMDWamp14ViewController7connectfS0_FT_T_ + 170
>     8   TestMDWamp                          0x000319e2 _TToFC10TestMDWamp14ViewController7connectfS0_FT_T_ + 34
>     9   libobjc.A.dylib                     0x0204c0b5 -[NSObject performSelector:withObject:withObject:] + 84
>     10  UIKit                               0x00b68b79 -[UIApplication sendAction:to:from:forEvent:] + 118
>     11  UIKit                               0x00b68af8 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
>     12  UIKit                               0x00d088f8 -[UIControl sendAction:to:forEvent:] + 79
>     13  UIKit                               0x00d08c78 -[UIControl _sendActionsForEvents:withEvent:] + 408
>     14  UIKit                               0x00d07c7e -[UIControl touchesEnded:withEvent:] + 714
>     15  UIKit                               0x00be5182 -[UIWindow _sendTouchesForEvent:] + 1095
>     16  UIKit                               0x00be6220 -[UIWindow sendEvent:] + 1159
>     17  UIKit                               0x00b8af93 -[UIApplication sendEvent:] + 266
>     18  UIKit                               0x00b60668 _UIApplicationHandleEventQueue + 7802
>     19  CoreFoundation                      0x0029d6ff __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
>     20  CoreFoundation                      0x0029338b __CFRunLoopDoSources0 + 523
>     21  CoreFoundation                      0x002927a8 __CFRunLoopRun + 1032
>     22  CoreFoundation                      0x002920e6 CFRunLoopRunSpecific + 470
>     23  CoreFoundation                      0x00291efb CFRunLoopRunInMode + 123
>     24  GraphicsServices                    0x0481b664 GSEventRunModal + 192
>     25  GraphicsServices                    0x0481b4a1 GSEventRun + 104
>     26  UIKit                               0x00b66bfa UIApplicationMain + 160
>     27  TestMDWamp                          0x0003409c main + 140
>     28  libdyld.dylib                       0x036caa21 start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by girishnair12345** [comment]
Now When I trun off the network and connect
> 2016-01-20 13:23:35.511 TestMDWamp[5359:56314] -[MDWamp transportDidFailWithError:] DID FAIL reason The operation couldn’t be completed. Network is down
> Session Closed  Code: 50
> Reason: The operation couldn’t be completed. Network is down

and i press connect again,
> 2016-01-20 13:23:54.483 TestMDWamp[5359:56314] *** Assertion failure in -[SRWebSocket open], <PATH>/Pods/SocketRocket/> SocketRocket/SRWebSocket.m:389
> 2016-01-20 13:23:54.488 TestMDWamp[5359:56314] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot call -(void)open on SRWebSocket more than once'
> *** First throw call stack:
> (
>     0   CoreFoundation                      0x00383a14 __exceptionPreprocess + 180
>     1   libobjc.A.dylib                     0x02037e02 objc_exception_throw + 50
>     2   CoreFoundation                      0x003838aa +[NSException raise:format:arguments:] + 138
>     3   Foundation                          0x007bfd26 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
>     4   SocketRocket                        0x001f85fb -[SRWebSocket open] + 379
>     5   MDWamp                              0x00194076 -[MDWampTransportWebSocket open] + 54
>     6   MDWamp                              0x0017b880 -[MDWamp connect] + 80
>     7   TestMDWamp                          0x0003199a _TFC10TestMDWamp14ViewController7connectfS0_FT_T_ + 170
>     8   TestMDWamp                          0x000319e2 _TToFC10TestMDWamp14ViewController7connectfS0_FT_T_ + 34
>     9   libobjc.A.dylib                     0x0204c0b5 -[NSObject performSelector:withObject:withObject:] + 84
>     10  UIKit                               0x00b68b79 -[UIApplication sendAction:to:from:forEvent:] + 118
>     11  UIKit                               0x00b68af8 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
>     12  UIKit                               0x00d088f8 -[UIControl sendAction:to:forEvent:] + 79
>     13  UIKit                               0x00d08c78 -[UIControl _sendActionsForEvents:withEvent:] + 408
>     14  UIKit                               0x00d07c7e -[UIControl touchesEnded:withEvent:] + 714
>     15  UIKit                               0x00be5182 -[UIWindow _sendTouchesForEvent:] + 1095
>     16  UIKit                               0x00be6220 -[UIWindow sendEvent:] + 1159
>     17  UIKit                               0x00b8af93 -[UIApplication sendEvent:] + 266
>     18  UIKit                               0x00b60668 _UIApplicationHandleEventQueue + 7802
>     19  CoreFoundation                      0x0029d6ff __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
>     20  CoreFoundation                      0x0029338b __CFRunLoopDoSources0 + 523
>     21  CoreFoundation                      0x002927a8 __CFRunLoopRun + 1032
>     22  CoreFoundation                      0x002920e6 CFRunLoopRunSpecific + 470
>     23  CoreFoundation                      0x00291efb CFRunLoopRunInMode + 123
>     24  GraphicsServices                    0x0481b664 GSEventRunModal + 192
>     25  GraphicsServices                    0x0481b4a1 GSEventRun + 104
>     26  UIKit                               0x00b66bfa UIApplicationMain + 160
>     27  TestMDWamp                          0x0003409c main + 140
>     28  libdyld.dylib                       0x036caa21 start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by mogui** [comment]
hi @girishnair12345 

> The demo project that you have doesnt run
> files are missing in that
File are not missing, you just have to init the git submodules to run it

Anyway I managed to reproduce your situation with wamp cra auth, I'll work to fix that, just one question, are you using `crossbar` as a server to test that? if yes can you attach the config file so I can test exactly your environment

Bests

**Comment by mogui** [comment]
@girishnair12345,
It's the way SRWebSocket works read here https://github.com/square/SocketRocket/issues/11 so I was modeling after it, and my demo works because when disconnected i use a new MDWamp object

but now I think it should work the way you need, being MDWamp managing SRWebSocket reinitialization within itself, it will take some times to have it but it will.

Temporarily you can just see the demo code and create a whole new MDWamp when re-connecting
