### ISSUE TITLE
Complete example

### ISSUE THREAD

**Issue by usirin** [mogui/MDWamp#4]
Hello,

I admire your work. It is really awesome what you are doing. But, i was wondering if you can provide some examples. I know your usage examples are well enough for someone, but a complete example to show how something done would be really awesome.

Thank you.

**Comment by VikranthKumar05** [comment]
let trans = MDWampTransportWebSocket(server: URL(string: "ws://myteambit.com/websocket")!, protocolVersions: [kMDWampProtocolWamp2msgpack, kMDWampProtocolWamp2json])
                let wamp = MDWamp(transport: trans, realm: "realm1", delegate: self)
                wamp?.connect()

Um getting
-[MDWamp transportDidFailWithError:] DID FAIL reason received bad response code from server 426
some("received bad response code from server 426")

Please Help!

**Comment by mogui** [comment]
HI there, 
it seems there's something wrong in the initial handshake with the server that's an error given from the server, could be something regarding protocol version? does the srver support Wamp 2 ?

**Comment by VikranthKumar05** [comment]
I am using XCode 9.4, Swift 4.1

This is how we implemented the server side. It is working in the web as well as Android.
http://socketo.me/docs/wamp

**Comment by mogui** [comment]
So you should know better than me what that server error means 
Quick search led me to this https://github.com/ratchetphp/Ratchet/issues/619
it seems to be a problem with Ratchet server that doesn't support WAMPv2 and this client dropped WAMPv1 support long ago

**Comment by VikranthKumar05** [comment]
Is there a version of MDWamp which could be used for Wampv1?

**Comment by mogui** [comment]
Version 1.1.0 was the last supporting it, I should do a branch for that I think, but it’s tagged gif you you want to use it.

**Comment by VikranthKumar05** [comment]
I am using cocoapod.

**Comment by VikranthKumar05** [comment]
![screen shot 2018-09-13 at 12 24 45 pm](https://user-images.githubusercontent.com/40295059/45471922-3472b700-b750-11e8-85c4-385542919880.png)

Couldn't find the v1.1.0 commit. So, Tried using cocoapod getting "'NSData+SRB64Additions.h' file not found"
