### ISSUE TITLE
Missing Parameters for deferredWampCRASigningBlock

### ISSUE THREAD

**Issue by fancy42** [mogui/MDWamp#40]
Hi,

[in this line](https://github.com/mogui/MDWamp/blob/46bd6c8ba240594950946189f14ece14d9bc7d4c/MDWamp/src/MDWamp.m#L564) it is checked whether or not a custom WampCRASigningBlock is provided.
However all that is passed as a parameter is the "challenge" extra of the MDWampChallenge.
When in fact I need the other ones, too: "salt", "iterations" and "keylen".

Could you pass the whole MDWampChallenge instead?

Kind regards,
Matthias

**Comment by mogui** [comment]
i'll have a look soon,
sorry for the delay

**Comment by mogui** [comment]
fixed with #41
