### ISSUE TITLE
dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)

### ISSUE THREAD

**Issue by fancy42** [mogui/MDWamp#42]
Since I added MDWamp, I get these kinds of errors. In the hundreds.
But only after the app ran for about an hour.
No clue what this means. Can somebody help me?

```
<Error>: tcp_connection_host_start 7181 DNSServiceGetAddrInfo failed: -65537
<Warning>: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
<Error>: tcp_connection_host_start 7182 DNSServiceGetAddrInfo failed: -65537
<Warning>: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
<Error>: tcp_connection_host_start 7182 DNSServiceGetAddrInfo failed: -65537
<Warning>: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
<Error>: tcp_connection_host_start 7183 DNSServiceGetAddrInfo failed: -65537
<Warning>: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
<Error>: tcp_connection_host_start 7183 DNSServiceGetAddrInfo failed: -65537
```

**Comment by mogui** [comment]
Hi @fancy42, 
that seems an error regarding  DNS Service Discovery `dnssd`
seems like the machine is trying to do some bonjour lookup and failing.
Something that doesn't have anything to deal with MDWamp.

I assume you're using the lib in a Mac app since you're saying that the app is running more than an hour. IN which context you are using the lib? give me more context, But I'm quite sure the problem isn't the library

**Comment by fancy42** [comment]
Hi @mogui ,
thanks for answering. I'm currently still investigating this.
I'm using it on the iPhone. 

The app is also using [Alamofire](https://github.com/Alamofire/Alamofire). And I found out by now that the Alamofire calls are failing. I actually can not promise that the MDWamp calls are failing, too.

I'm trying to get the app to fail while debugging to maybe gain more insight.

I will post updates here. If I find out it's not MDWamp related, I apologise and close this thread.
If someone has ideas that might help me with the investigation, I'm all ears :)

**Comment by fancy42** [comment]
I FINALLY figured it out. My app was using up File Descriptors like crazy because SSL Handshakes failed and I was reconnecting all the time. Is this a bug in MDWamp? This is probably rather rare, but may be worth investigating why MDWamp is leaking File Descriptors like that.
This was really hard to reproduce because when the build Scheme was set to Debug, the SSL Handshake did not fail...

This Apple Developer Forum thread describes how I figured it out https://forums.developer.apple.com/message/118647#118647
