### ISSUE TITLE
negotiated protocol is (null)

### ISSUE THREAD

**Issue by khaled-mohamed** [mogui/MDWamp#43]
I integrate MDWamp Library in my  Project as example but it does not establish connection and return this error  

-[MDWampTransportWebSocket webSocketDidOpen:] negotiated protocol is (null)
2016-02-29 09:14:46.761 WampSocket[1119:129476] *** Terminating app due to uncaught exception 'it.mogui.mdwamp', reason: 'Wrong message recived'

**Comment by khaled-mohamed** [comment]
I check in  
- (void)transportDidReceiveMessage:(NSData *)message

it returns [0,"93563719456d3f8a194e1d805417130",1,"Ratchet\/0.3.3"]

**Comment by mogui** [comment]
mmm Is Ratchet configured to talk WAMP protocol?
I don't know how Ratchet works if it's default is WAMP or not, but it seems it sends a malformed message, that exception get raised when the client receive a non WAMP message

**Comment by mogui** [comment]
Oh, by looking at 
> it returns [0,"93563719456d3f8a194e1d805417130",1,"Ratchet\/0.3.3"]
and 
http://socketo.me/docs/wamp

I see that Ratchet is speaking WAMPv1 that is DEPRECATED and not supported anymore by MDWamp 
sorry 
If you want a modern PHP wamp server have a look at http://wamp-proto.org/implementations/

**Comment by avinashvaghasiya** [comment]
solw this issue??
