### ISSUE TITLE
Register RPCs not giving any callbacks after registering

### ISSUE THREAD

**Issue by girishnair12345** [mogui/MDWamp#45]
Whenever I register an RPC I get an success callback for registration and error if i try to re-register the RPC but I am not getting a callbacks from the server for invocations made from the server for that URI

**Comment by mogui** [comment]
hi @girishnair12345 
I'll try to split your question in two pieces:
> Whenever I register an RPC I get an success callback for registration and error if i try to re-register the RPC
that is correct you cannote re register an RPC

> I am not getting a callbacks from the server for invocations made from the server for that URI

I don't get the context of what you're trying if you register a callback from the iOS/Mac client, you have to invoke from another client and the callback will be invoked on the client that registered the RPC not the server. Can you try to explain with more details your issue please ?

bests

**Comment by girishnair12345** [comment]
Once i register the URI, I am not getting callbacks on that URI after successful registering

Eg
[wamp registerRPC:@"com.example.procedure1" procedure:^(MDWamp *client, MDWampInvocation *invocation) {
        // Call back not received here after successfully registering the URI
    } cancelHandler:^{
    } registerResult:^(NSError *error) {
    }];

**Comment by mogui** [comment]
@girishnair12345 
the callback will be invoked when ANOTHER client invokes the procedure you have registered.
with that call you **register** a callback, the callback then has to be **invoked** by someone. It's this way RPC works

**Comment by girishnair12345** [comment]
Yes i know that but for some reason when the server is invoking that callback I am not able to receive it at my end

**Comment by girishnair12345** [comment]
It was typo, registered URI was having an extra character
